### ISSUE TITLE
Add python class for query clients

### ISSUE THREAD

**Issue by timokau** [timokau/prefq#51]
It should be possible to implement a python query client without manually sending any requests. We should provide a `QueryClient` class that provides methods such as `send_query` which query clients can use.

Related to #50.

**Comment by patrickab** [comment]
Taking another look at our implemantation of `static_queries.py` I noticed, that actually we would need a possibility to sort the queries received from the server. In this specific example it makes no difference to not do so, as the videos `01.mp4` [...] `10.mp4` & their resulting Query-IDs

`01-02-left`, `01-02-right`
[...]
`09-10-left`, `09-10-right`

are alphanumerically sorted in the same order, as they are sent to the server - however, in a general usecase of static queries, this can not be expected.

I've got different ideas in mind, the question is, how can we make this as userfriendly as possible & generalize behavior at the same time, without restructuring the code too much - the catch is, that in the imitation example, the gatherer already has such a dictionary, if we now implement a generalized solution, we would no longer have the easiest solution inside the Imitation Example. I think this is not optimal, as many people might want to use Imitation, so here we might want to stick to the easiest solution, which is the status quo.

I think the best solution would be to provide a function query_client.generate_queryIDs(video_pairs), that takes a List of videofilename-tuples, & converts it to a dictionary of Query IDs, that looks exactly as the one inside the Imitation Example - this could happen inside the QueryClient, so that the user just needs to call `query_client.sort(feedback_data)`

**Comment by patrickab** [comment]
another idea would be to name the videos in an ascending order, when generating them, in other words using

```python
        for i, (query_id, query) in enumerate(self.pending_queries.items()):
            write_fragment_video(
                query[0],
                frames_per_second=self.frames_per_second,
                output_path=os.path.join(self.video_dir, f"{i}.webm"),
            )
            write_fragment_video(
                query[1],
                frames_per_second=self.frames_per_second,
                output_path=os.path.join(self.video_dir, f"{i+1}.webm"),
            )
```
and adding padding to the indices, by specifying `f"{str({i}).zfill(3)}.webm`

instead of

```python
        for i, (query_id, query) in enumerate(self.pending_queries.items()):
            write_fragment_video(
                query[0],
                frames_per_second=self.frames_per_second,
                output_path=os.path.join(self.video_dir, f"{query_id}-left.webm"),
            )
            write_fragment_video(
                query[1],
                frames_per_second=self.frames_per_second,
                output_path=os.path.join(self.video_dir, f"{query_id}-right.webm"),
            )
```

**Comment by timokau** [comment]
I do not quite understand the issue. We use query IDs in both examples right? Why do we need to sort the quries and why can we not use the query IDs to do this?

**Comment by patrickab** [comment]
within the imitation example, when we receive feedback, we need to order our feedback, in the same sequence, as we've send the queries. Thats because we're returning a np_array, where `np_array[i]` needs to correspond to `query_id[i]` - however, `flask.jsonify()` orders queries alphanumerically before sending them back to the query client.

Within the static query example we don't necessarily need ordered queries, given that we're not learning anything here. However, a potential future user might expect the queries to arrive in the same order as he/she sent them. Therefore, we should either guarantee ordered feedback, or document, that feedback is not ordered.

**Comment by timokau** [comment]
I understand, but why is that a problem? The `QueryClient` class could have a `poll_feedback` function that just returns a dictionary mapping query IDs to responses. That way, no ordering is implied.
